// <auto-generated />
using ExamWeb_NguyenMinhQuan.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExamWeb_NguyenMinhQuan.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250611022101_InitSchema")]
    partial class InitSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ExamWeb_NguyenMinhQuan.Models.Phim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DienVien")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("GiaVe")
                        .HasColumnType("float");

                    b.Property<int>("ThoiLuong")
                        .HasColumnType("int");

                    b.Property<bool>("TrongNuoc")
                        .HasColumnType("bit");

                    b.Property<string>("Tuade")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Phims");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DienVien = "Son Ye Jin, Hyun Bin",
                            GiaVe = 120000.5,
                            ThoiLuong = 120,
                            TrongNuoc = false,
                            Tuade = "Hạ cánh nơi anh"
                        },
                        new
                        {
                            Id = 2,
                            DienVien = "Trần Phương Anh, Đông Nhi",
                            GiaVe = 100000.0,
                            ThoiLuong = 105,
                            TrongNuoc = true,
                            Tuade = "Mắt biếc"
                        },
                        new
                        {
                            Id = 3,
                            DienVien = "Song Kang Ho",
                            GiaVe = 150000.0,
                            ThoiLuong = 132,
                            TrongNuoc = false,
                            Tuade = "Parasite"
                        },
                        new
                        {
                            Id = 4,
                            DienVien = "Leonardo DiCaprio",
                            GiaVe = 200000.0,
                            ThoiLuong = 195,
                            TrongNuoc = false,
                            Tuade = "Titanic"
                        },
                        new
                        {
                            Id = 5,
                            DienVien = "Trấn Thành, Kiều Minh Tuấn",
                            GiaVe = 90000.0,
                            ThoiLuong = 130,
                            TrongNuoc = true,
                            Tuade = "Bố già"
                        },
                        new
                        {
                            Id = 6,
                            DienVien = "Nhã Phương",
                            GiaVe = 110000.0,
                            ThoiLuong = 115,
                            TrongNuoc = true,
                            Tuade = "Gái già lắm chiêu"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
